security:
    # Password hashers (not needed for workers, but required by Symfony)
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User providers
    providers:
        worker_provider:
            entity:
                class: App\Domain\WorkCycle\Entity\Worker
                property: id

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        worker:
            pattern: ^/worker
            lazy: true
            provider: worker_provider
            custom_authenticators:
                - App\Security\WorkerAuthenticator

        main:
            lazy: true

    # Access control
    access_control:
        - { path: ^/worker, roles: PUBLIC_ACCESS }
        # - { path: ^/admin, roles: ROLE_ADMIN } # Future: add admin authentication
